apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvshka
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pvolume
  persistentVolumeReclaimPolicy: Retain